spring:
  profiles:
    active: dev

  main:
    lazy-initialization: true      # Load beans only when needed
    banner-mode: off               # Hide Spring Boot banner

  devtools:
    add-properties: false
    restart:
      enabled: false               # Disable devtools restart (faster startup)

  application:
    name: summer-internship

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://34.165.99.109/postgres
    username: postgres
    password: umut62
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: mertdamburaci1@gmail.com
    password: wexewroagdpagyoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

okta:
  oauth2:
    client:
      registration:
        auth0:
          issuer: https://dev-rswrfezhup08dw27.us.auth0.com/
          client-id: eXTU0IJkmyPzsfemoiACekMJkXIIdeZq
          client-secret: LO9qrprGxMNLvwit9W23amOXeeBiJ3I2K2XQu-9QFDVDzaEjmXKw0W6cyIYPZsHz
          scope: openid,profile,email

logging:
  level:
    ROOT: info
    org:
      springframework:
        security: warn
      hibernate:
        SQL: warn
        type:
          descriptor:
            sql: off
    gp.graduationproject.summer_internship_back: info